# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
# Fabric Properties
# check these on https://modmuss50.me/fabric.html
minecraft_version=1.21.4
yarn_mappings=1.21.4+build.8
loader_version=0.16.10
# Mod Properties
mod_version=0.0.3
maven_group=org.yang
archives_base_name=interestingworld
# Dependencies
# check this on https://modmuss50.me/fabric.html
fabric_version=0.115.1+1.21.4

rei_version=18.0.796
sodium_modrinth_version=mc1.21.4-0.6.7-fabric
tweakeroo_modrinth_version=0.23.1
minihud_modrinth_version=0.34.3
malilib_modrinth_version=0.23.1
jade_modrinth_version=17.2.2+fabric
fiber_version=0.23.0-2
neat_curseforge_id=6050530